<div class="row">
    <div class="col-md-12">
        Hello,
        <br/><br/>
        A backup of your organization {{ $orgName }}'s data has just been generated by {{ $createdBy }} with description {{ $backupDesc }}.
        <br/><br/>
        Regards,
        <br/><br/>
        Team HyLyt
        {!! $systemLogoHtml !!}
        {!! $disclaimerHtml !!}
    </div>
</div>